// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv0yGyKzKCkWPqvBC5M24gN0bHX9PiAjM',
    appId: '1:146108150432:web:9a8777f6934ef8def8cfc5',
    messagingSenderId: '146108150432',
    projectId: 'squadhub-b8655',
    authDomain: 'squadhub-b8655.firebaseapp.com',
    storageBucket: 'squadhub-b8655.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHyoh_69IbgHV8KhKQC-vbbciu708IU_c',
    appId: '1:146108150432:android:6cc082498d1a63a3f8cfc5',
    messagingSenderId: '146108150432',
    projectId: 'squadhub-b8655',
    storageBucket: 'squadhub-b8655.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0ByK6pN61AYrUVluFBPocpBgYbqU76gE',
    appId: '1:146108150432:ios:10001e1e46a9961af8cfc5',
    messagingSenderId: '146108150432',
    projectId: 'squadhub-b8655',
    storageBucket: 'squadhub-b8655.firebasestorage.app',
    iosBundleId: 'com.example.squadhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0ByK6pN61AYrUVluFBPocpBgYbqU76gE',
    appId: '1:146108150432:ios:10001e1e46a9961af8cfc5',
    messagingSenderId: '146108150432',
    projectId: 'squadhub-b8655',
    storageBucket: 'squadhub-b8655.firebasestorage.app',
    iosBundleId: 'com.example.squadhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv0yGyKzKCkWPqvBC5M24gN0bHX9PiAjM',
    appId: '1:146108150432:web:86c3b273a8488aadf8cfc5',
    messagingSenderId: '146108150432',
    projectId: 'squadhub-b8655',
    authDomain: 'squadhub-b8655.firebaseapp.com',
    storageBucket: 'squadhub-b8655.firebasestorage.app',
  );
}
